name: Publish as npm module
on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add @d4l/js-crypto deploy key
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.JS_CRYPTO_DEPLOY_KEY }}

      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
          registry-url: https://registry.npmjs.org/

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Check if version has been updated
        uses: EndBug/version-check@v1
        id: check
        with:
          diff-search: true
          file-name: package.json

      - name: Install
        if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Publish
        if: steps.check.outputs.changed == 'true'
        run: cd dest && npm publish --access restricted && cd -
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
